version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  api:
    container_name: api
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
