version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  openboot:
    container_name: openboot
    build: .
    restart: always
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - mongodb
  nlp:
    container_name: nlp
    build: nlp
    restart: always
    ports:
      - "8081:8081"
    expose:
      - 8081
    depends_on:
      - openboot
