version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  open-assistant-service:
    container_name: openassistant-service
    build: open-assistant-service
    restart: always
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - npl
  nlp:
    container_name: nlp
    build: nlp
    restart: always
    ports:
      - "8081:8081"
    expose:
      - 8081
  telegram-bot-service:
    container_name: telegram-bot-service
    build: telegram-bot-service
  restart: always
    ports:
      - "8082:8082"
    expose:
      - 8082
    depends_on:
      - openassistant-service
