openapi: 3.0.0
info:
  version: 0.0.1
  title: Open Boot
  description: Chatbot for quickly finding answers to questions.
  contact:
    name: Sherzod Mamadaliev
    email: egnaf@yahoo.com
    url: https://github.com/egnaf
servers:
  - url: https://openboot.com/api/chat/v1

paths:
  # TODO: Add endpoints

components:
  # TODO: Add models
